### ISSUE TITLE
Should you increment the tries at this point?

### ISSUE THREAD

**Issue by mayisa87** [pothigai/HangManApp#3]
https://github.com/pothigai/HangManApp/blob/79e2398e13375d4859492cb57e1bc6e1a0dd1f48/HangManApp/Program.cs#L61

You do not increment the tries count in case, that the user guessed a letter correctly. But, if user entered the last remaining letter right, you jump into this if statement, and do increment the tries counter. So this is a bit of an inconsistency to me

**Comment by pothigai** [comment]
I'm still unsure about removing this increment, because even if the user guessed the last remaining letter correctly, it should still count as a guess, right? For example, if the user has completed 8 guesses, and there's one letter remaining, and the user then guesses the last letter to complete the game, they will have taken a total of 9 guesses to get the correct word.

**Comment by incredibleLeitman** [comment]
![image](https://github.com/pothigai/HangManApp/assets/24638443/804c590f-57f8-40b0-ab2f-411fc537f097)
Currently you have the increment as duplicated code in both branches of the condition which means you could move it out (if in both cases you execute some statement this means you can execute it always right?)

Think about *when* exactly a user takes a guess?

**Comment by incredibleLeitman** [comment]
> Think about when exactly a user takes a guess?

This was meant as a real question for you to think about, not just remove one line and close the issue :D
What I was referring to was, that currently you increase the tries counter *after detecting that the secret word still contains a filler char*. This obviously works fine 👍 

But logically this does not belong there -> Instead you should increase the counter where it happens: If the user has guessed a letter that results in a lost try -> increase the counter.

**Comment by pothigai** [comment]
Ahh, my bad, yea I understand now. Basically everytime a user enters a letter that I deem as valid, then the count should be incremented, so now I have moved it out into just the main while loop.

**Comment by incredibleLeitman** [comment]
Yeah you understand 👍 :D

But I would even move it a few lines above. Consider the following behaviour:
![image](https://github.com/pothigai/HangManApp/assets/24638443/dc2f1e75-59c1-41f5-9203-c00e64f279d5)

Usually I would put it directly after 1 -> the user guesses a letter, the count increases.
But because you do not treat already guessed letters as an attempt at 2 you need to move it down to 3 before or after adding the letter to the list.

Now that you have the increment after the check if the word was fully guessed (that contains a return) it happens the the user guesses a letter and when solving the word get the output "You used a total of triesCount ..." with one less guess than actually.
